package org.wilkretawesomesauce.minestuckuniverseported.mechanics.timeline;

import com.mojang.logging.LogUtils;
import net.commoble.infiniverse.api.InfiniverseAPI;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.dimension.DimensionType;
import net.minecraft.world.level.dimension.LevelStem;
import net.minecraft.world.level.storage.LevelResource;
import org.slf4j.Logger;
import org.wilkretawesomesauce.minestuckuniverseported.util.MSUAttachments;
import org.wilkretawesomesauce.minestuckuniverseported.Minestuckuniverseported;

import javax.annotation.Nullable;
import java.io.IOException;
import java.nio.file.FileVisitResult;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.List;
import java.util.UUID;

/**
 * Forks a brand-new parallel timeline branch from the current live state of an existing level (Alpha
 * or any other branch - see {@link TimelineBranch}'s doc comment on arbitrary tree depth), by literally
 * copying that dimension's on-disk save folder into a freshly-registered dimension via Infiniverse
 * ({@code net.commoble.infiniverse}, already a mandatory dependency of this project - see Minestuck's
 * own {@code DynamicDimensions}/Land system for the confirmed-working reference this is modeled on).
 * <p>
 * Unlike Minestuck's Lands (always freshly-generated terrain, never copied), this genuinely forks the
 * source dimension's <i>current</i> state - the new branch starts out identical to its source, not
 * empty. This is unproven territory for this project (see {@code CLAUDE.md}'s "known risks" for this
 * feature) - the source is force-saved synchronously immediately before the copy specifically so the
 * copy is a consistent snapshot, not a race against still-dirty chunks.
 */
public final class BranchForker
{
	private static final Logger LOGGER = LogUtils.getLogger();

	// DimensionType.getStorageFolder special-cases the Overworld to return the WORLD SAVE ROOT itself
	// (region/entities/poi sit directly under it, alongside level.dat, playerdata/, every other
	// dimension's own folder, etc) - unlike every other dimension, which gets a genuinely self-contained
	// folder. A blind recursive copy of "the source dimension's folder" would, for an Overworld source,
	// copy the ENTIRE save (including every other existing branch) into the new branch. Forking from
	// Alpha instead copies just these three subfolders directly - the same region/entities/poi data any
	// non-overworld dimension folder contains on its own.
	private static final List<String> LEVEL_SUBFOLDERS = List.of("region", "entities", "poi");

	private BranchForker()
	{
	}

	/**
	 * @param name the branch's display name (already resolved/auto-generated by the caller - this
	 *             class doesn't invent names, see {@code TechTimelineBranch}/{@code TimelineBranchCommand})
	 * @return the new branch's metadata, or {@code null} if forking failed (logged; caller shows a
	 *         generic failure message the same way {@code TimelineManager.rewind} does for its own failures)
	 */
	@Nullable
	public static TimelineBranch fork(ServerPlayer creator, ServerLevel source, String name)
	{
		MinecraftServer server = source.getServer();

		// Synchronous flush (confirmed via ServerLevel#save's body: flush=true blocks on
		// IOUtilities.waitUntilIOWorkerComplete()) - safe to immediately follow with a raw file copy.
		source.save(null, true, false);

		TimelineBranchRegistry registry = server.overworld().getData(MSUAttachments.TIMELINE_BRANCHES);
		TimelineBranch sourceBranch = registry.findByDimension(source.dimension());
		UUID parentBranchId = sourceBranch != null ? sourceBranch.getId() : null;

		Path worldRoot = server.getWorldPath(LevelResource.ROOT);
		Path sourceFolder = DimensionType.getStorageFolder(source.dimension(), worldRoot);

		String slug = sanitizeSlug(name);
		ResourceKey<Level> destKey = null;
		Path destFolder = null;
		for(int n = 0; ; n++)
		{
			String path = "branch/" + slug + (n == 0 ? "" : "_" + n);
			ResourceKey<Level> candidate = ResourceKey.create(Registries.DIMENSION, Minestuckuniverseported.id(path));
			Path candidateFolder = DimensionType.getStorageFolder(candidate, worldRoot);
			if(server.getLevel(candidate) == null && Files.notExists(candidateFolder))
			{
				destKey = candidate;
				destFolder = candidateFolder;
				break;
			}
		}

		try
		{
			copyDimensionFolder(source.dimension(), sourceFolder, destFolder);
		}
		catch(IOException e)
		{
			LOGGER.error("Failed to fork timeline branch '{}' (copying {} -> {})", name, sourceFolder, destFolder, e);
			return null;
		}

		ServerLevel newLevel = InfiniverseAPI.get().getOrCreateLevel(server, destKey,
				() -> new LevelStem(source.dimensionTypeRegistration(), source.getChunkSource().getGenerator()));

		TimelineBranch branch = new TimelineBranch(UUID.randomUUID(), destKey, name, parentBranchId,
				creator.getUUID(), server.overworld().getGameTime(), true, 0L);
		registry.add(branch);

		creator.teleportTo(newLevel, creator.getX(), creator.getY(), creator.getZ(), creator.getYRot(), creator.getXRot());

		return branch;
	}

	/**
	 * Re-registers a dormant branch's level (see {@link BranchLifecycleEvents} for how it went dormant
	 * in the first place) by calling {@code getOrCreateLevel} again - since dormancy only unregisters
	 * the live {@code ServerLevel}/registry entry and never touches the on-disk folder, this reloads the
	 * exact existing save data via ordinary vanilla region loading, not fresh generation. The
	 * {@link LevelStem} supplier is rebuilt from the branch's parent (or Alpha) since the original
	 * in-memory {@code LevelStem} from fork-time is gone once unregistered.
	 */
	public static ServerLevel reactivate(MinecraftServer server, TimelineBranch branch)
	{
		ServerLevel parentLevel = resolveParentLevel(server, branch);
		ServerLevel newLevel = InfiniverseAPI.get().getOrCreateLevel(server, branch.getDimensionKey(),
				() -> new LevelStem(parentLevel.dimensionTypeRegistration(), parentLevel.getChunkSource().getGenerator()));
		branch.setRegistered(true);
		return newLevel;
	}

	/**
	 * Resolves {@code branch}'s level, reactivating it via {@link #reactivate} first if it's currently
	 * dormant - shared by {@code TimelineBranchCommand}'s {@code travel} and {@code TechTimelineBranch}'s
	 * "return to parent" action, so both go through the exact same dormant-check-and-reactivate path.
	 */
	public static ServerLevel travelTo(MinecraftServer server, TimelineBranch branch)
	{
		if(branch.isRegistered())
		{
			ServerLevel level = server.getLevel(branch.getDimensionKey());
			if(level != null)
				return level;
		}
		return reactivate(server, branch);
	}

	/** Also used by {@link BranchDeleter} to find somewhere safe to evict players from a deleted branch. */
	static ServerLevel resolveParentLevel(MinecraftServer server, TimelineBranch branch)
	{
		UUID parentId = branch.getParentBranchId();
		if(parentId == null)
			return server.overworld();

		TimelineBranchRegistry registry = server.overworld().getData(MSUAttachments.TIMELINE_BRANCHES);
		TimelineBranch parent = registry.get(parentId);
		if(parent == null)
			return server.overworld();

		ServerLevel parentLevel = server.getLevel(parent.getDimensionKey());
		return parentLevel != null ? parentLevel : resolveParentLevel(server, parent);
	}

	/**
	 * Shared naming scheme used both by {@code TechTimelineBranch}'s PRESS action (no text-input GUI
	 * exists to ask the player for a name) and {@code TimelineBranchCommand}'s {@code create} when no
	 * name argument is given.
	 */
	public static String autoName(ServerPlayer player, TimelineBranchRegistry registry)
	{
		int count = registry.countCreatedBy(player.getUUID()) + 1;
		return player.getName().getString() + "'s Branch #" + count;
	}

	private static String sanitizeSlug(String name)
	{
		String slug = name.toLowerCase(java.util.Locale.ROOT).replaceAll("[^a-z0-9_.-]", "_");
		return slug.isBlank() ? "branch" : slug;
	}

	private static void copyDimensionFolder(ResourceKey<Level> sourceKey, Path sourceFolder, Path destFolder) throws IOException
	{
		if(sourceKey == Level.OVERWORLD)
		{
			Files.createDirectories(destFolder);
			for(String sub : LEVEL_SUBFOLDERS)
			{
				Path sourceSub = sourceFolder.resolve(sub);
				if(Files.exists(sourceSub))
					copyRecursively(sourceSub, destFolder.resolve(sub));
			}
		}
		else
		{
			copyRecursively(sourceFolder, destFolder);
		}
	}

	private static void copyRecursively(Path source, Path dest) throws IOException
	{
		Files.walkFileTree(source, new SimpleFileVisitor<>()
		{
			@Override
			public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) throws IOException
			{
				Files.createDirectories(dest.resolve(source.relativize(dir)));
				return FileVisitResult.CONTINUE;
			}

			@Override
			public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException
			{
				Files.copy(file, dest.resolve(source.relativize(file)));
				return FileVisitResult.CONTINUE;
			}
		});
	}
}
